### ISSUE TITLE
Metabase

### ISSUE THREAD

**Issue by danigulyas** [sztupy/valasztas-adatbazis#4]
Kiraly repo, kosz! Lattam hogy az adatok alapjan Google Sheets-ben dolgoznak az emberek ami lassu es nem tul flexible.

Felhuztam egy [Metabase](https://www.metabase.com/)-t [ide](http://35.186.195.79/), ha van load skalazhato, public (opcionalisan embeddelheto) linket lehet dashboardokrol kerni.

Account: `tumbla@valasztasibigdata.hu` : `2NPneMXhli7Bs4`, let me know ha ez segit / valamit varazsoljak meg rajta.

**Comment by danigulyas** [comment]
ps: a tablanevek auto derivaltak a roviditesekbol, eleg kuszak, ha valaki ert a domainhez es vallalkozna a rename-re, dm me! <3

**Comment by danigulyas** [comment]
![image](https://user-images.githubusercontent.com/10425681/38612143-11fe121c-3d86-11e8-8111-80a5f890e66a.png)

Szivesen plotolnam pl az anomaliakat egy mapen ezzel, de a beteg cloumn neveket nem tudom dekodolni. :(

**Comment by sztupy** [comment]
Úgy látom a pártdelegált lista még nem a legfrisebb adatokból lett feltöltve, az újban már van maz/taz/sorsz is, ami kell a szavazókörökhöz összekötéshez

**Comment by sztupy** [comment]
Van amúgy dokumentáció a táblákhoz: https://drive.google.com/file/d/1mop-hbQh9bDjyklwEUD1ana-KYne6M0j/view

**Comment by danigulyas** [comment]
Updateltem latestre, dokumentalom a columokat meg a tablakat.

**Comment by danigulyas** [comment]
Elkezdtem atnevezni a recordokat meg mappelni a relaciokat.

**Comment by danigulyas** [comment]
Uh, agyrem ahogyan publisholtak ezt, biztosan a UX-re es az atlathatosagra gondoltak :(
